apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: backend
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: backend
#  name: pv001
#spec:
#  capacity:
#    storage: 100Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Delete
#  storageClassName: local-storage
#  local:
#    path: /mnt/disks
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - k8s-node01